#include "../themes/defaultheader.yaml"
#include "../themes/defaultlighting.yaml"
#include "../themes/defaultplacenames.yaml"
#include "../themes/defaultvehicles.yaml"
#include "../themes/defaultwater.yaml"
#include "../themes/mapmode.yaml"
#include "../themes/sanfrancisco.yaml"
#include "../themes/canada.yaml"
#include "../themes/japanvehicles.yaml"
#include "../themes/japan.yaml"
#include "../themes/japansouth.yaml"
#include "../themes/japannorth.yaml"
#include "../themes/barcelona.yaml"
#include "../themes/london.yaml"
#include "../themes/paris.yaml"
#include "../themes/melbourne.yaml"
#include "../themes/newyork.yaml"
#include "../themes/phoenix.yaml"
#include "../themes/mountrush.yaml"
#include "../themes/brazilvehicles.yaml"
#include "../themes/brazil.yaml"
#include "../themes/germany.yaml"
#include "../themes/dubai.yaml"
#include "../themes/italy.yaml"
#include "../themes/Scandinavia.yaml"
#include "../themes/Thailand.yaml"
#include "../themes/hongkong.yaml"
#include "../themes/china.yaml"
    
ThemeManifest:
   <<: *DefaultHeader
   Themes: [
        *SummerSanFrancisco,
        *SpringSanFrancisco, 
        *AutumnSanFrancisco, 
        *WinterSanFrancisco, 

        *SummerCanada, 
        *SpringCanada, 
        *AutumnCanada, 
        *WinterCanada,

        *SummerJapanSouth, 
        *SpringJapanSouth, 
        *AutumnJapanSouth, 
        *WinterJapanSouth, 

        *SummerJapanNorth, 
        *SpringJapanNorth, 
        *AutumnJapanNorth, 
        *WinterJapanNorth, 

        *SummerJapan, 
        *SpringJapan, 
        *AutumnJapan, 
        *WinterJapan, 

        *SummerBarcelona, 
        *SpringBarcelona, 
        *AutumnBarcelona, 
        *WinterBarcelona, 

        *SummerLondon, 
        *SpringLondon, 
        *AutumnLondon, 
        *WinterLondon, 

        *SummerParis, 
        *SpringParis, 
        *AutumnParis, 
        *WinterParis, 

        *SummerMelbourne, 
        *SpringMelbourne, 
        *AutumnMelbourne, 
        *WinterMelbourne, 

        *SummerNewYork, 
        *SpringNewYork, 
        *AutumnNewYork, 
        *WinterNewYork, 

        *SummerPhoenix, 
        *SpringPhoenix, 
        *AutumnPhoenix, 
        *WinterPhoenix, 

        *SummerMountRush, 
        *SpringMountRush, 
        *AutumnMountRush, 
        *WinterMountRush,

        *SummerBrazil,
        *SpringBrazil,
        *AutumnBrazil,
        *WinterBrazil,

        *SummerGermany,
        *SpringGermany,
        *AutumnGermany,
        *WinterGermany,

        *SummerItaly,
        *SpringItaly,
        *AutumnItaly,
        *WinterItaly,
        
        *SummerScandinavia,
        *SpringScandinavia,
        *AutumnScandinavia,
        *WinterScandinavia,
        
        *SummerDubai,
        *SpringDubai,
        *AutumnDubai,
        *WinterDubai,
        
        *SummerThailand,
        *SpringThailand,
        *AutumnThailand,
        *WinterThailand,

        *Summerhongkong,
        *Springhongkong,
        *Autumnhongkong,
        *Winterhongkong,

        *Summerchina,
        *Springchina,
        *Autumnchina,
        *Winterchina
        ]
